# Generated by Django 5.0.3 on 2024-03-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_employee_emp_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_contact',
            field=models.CharField(default=1234567891, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_designation',
            field=models.CharField(choices=[('Jr. PHP Laravel Developer\t', 'Jr. PHP Laravel Developer'), ('Sr. Developer', 'Sr. Developer'), ('Content Writer', 'Content Writer'), ('Product Manager', 'Product Manager'), ('Admin', 'Admin'), ('UI/UX Designer', 'UI/UX Designer'), ('Jr. Web Designer', 'Jr. Web Designer'), ('Sr. HR Executive', 'Sr. HR Executive'), ('Sr. SEO Executive', '\tSr. SEO Executive'), ('Jr. HR Executive', 'Jr. HR Executive'), ('Lead Generation Executive', 'Lead Generation Executive'), ('Tech Lead', 'Tech Lead'), ('Trainee', 'Trainee'), ('Jr.React Native Developer', 'Jr.React Native Developer'), ('Intern', 'Intern'), ('Web Designer', 'Web Designer'), ('Project Manager', 'Project Manager'), ('SEO Executive', 'SEO Executive'), ('Quality Engineer', 'Quality Engineer'), ('Jr. PHP Laravel Developer', 'Jr. PHP Laravel Developer'), ('Quality Engineer Lead', 'Quality Engineer Lead'), ('Python Developer', 'Python Developer'), ('CEO', 'CEO'), ('COO', 'COO')], help_text='Employee Designation', max_length=70),
        ),
    ]
