# Generated by Django 5.0.3 on 2024-03-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employee_emp_contact_alter_employee_emp_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_designation',
            field=models.CharField(choices=[('Lead Generation Executive', 'Lead Generation Executive'), ('SEO Executive', 'SEO Executive'), ('Intern', 'Intern'), ('Python Developer', 'Python Developer'), ('Jr. PHP Laravel Developer\t', 'Jr. PHP Laravel Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Jr.React Native Developer', 'Jr.React Native Developer'), ('Project Manager', 'Project Manager'), ('COO', 'COO'), ('Product Manager', 'Product Manager'), ('Trainee', 'Trainee'), ('CEO', 'CEO'), ('Jr. HR Executive', 'Jr. HR Executive'), ('Web Designer', 'Web Designer'), ('Jr. Web Designer', 'Jr. Web Designer'), ('Jr. PHP Laravel Developer', 'Jr. PHP Laravel Developer'), ('Sr. SEO Executive', '\tSr. SEO Executive'), ('Quality Engineer Lead', 'Quality Engineer Lead'), ('Sr. HR Executive', 'Sr. HR Executive'), ('Tech Lead', 'Tech Lead'), ('Quality Engineer', 'Quality Engineer'), ('Sr. Developer', 'Sr. Developer'), ('Admin', 'Admin'), ('Content Writer', 'Content Writer')], help_text='Employee Designation', max_length=70),
        ),
    ]
